"use client";
import {useMemo} from "react";
import * as XLSX from "xlsx";
import type {IntelligenceResult} from "../../lib/api";

type Props={tab:string;result:IntelligenceResult;datasetName?:string;onSelect:(value:any)=>void};

function downloadXlsx(name:string, rows:any[][]){const ws=XLSX.utils.aoa_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Gamur");XLSX.writeFile(wb,`${name}.xlsx`)}
function Chart({chart}:{chart:any}){const d=(chart?.data||[]).filter((p:any)=>Number.isFinite(Number(p[chart.xKey]))&&Number.isFinite(Number(p[chart.yKey])));if(!d.length)return <div className="chartEmpty">No visual evidence available</div>;const ys=d.map((p:any)=>Number(p[chart.yKey]));const ymin=Math.min(...ys),ymax=Math.max(...ys),range=Math.max(1,ymax-ymin);return <div className="chartCanvas"><svg viewBox="0 0 640 230" role="img" aria-label={chart.title}><line x1="48" y1="15" x2="48" y2="200"/><line x1="48" y1="200" x2="625" y2="200"/><line x1="48" y1="108" x2="625" y2="108"/>{chart.type==="scatter"?d.slice(0,180).map((p:any,i:number)=><circle key={i} cx={55+(i/Math.max(1,d.length-1))*565} cy={195-((Number(p[chart.yKey])-ymin)/range)*175} r="3"/>):<polyline fill="none" stroke="currentColor" strokeWidth="3" points={d.map((p:any,i:number)=>`${55+(i/Math.max(1,d.length-1))*565},${195-((Number(p[chart.yKey])-ymin)/range)*175}`).join(" ")}/>}</svg><div className="chartAxes"><span>{chart.xKey}</span><span>{chart.yKey} · {ymin.toFixed(1)}–{ymax.toFixed(1)}</span></div></div>}

export default function ArtifactViews({tab,result,datasetName,onSelect}:Props){
 const charts=result.visualization?.charts||[];const rels=result.analysis?.relationships||result.visualization?.relationships||[];const stats=result.analysis?.summary||[];const questions=result.questions||[];const outliers=result.analysis?.outliers||[];const target=result.analysis?.target||null;
 const totalOutliers=useMemo(()=>outliers.reduce((n,x)=>n+x.count,0),[outliers]);
 if(tab==="visualize") return <div className="artifactView"><div className="artifactHero"><span className="sectionTag">VISUAL EXPLORATION</span><h2>See what is happening in the data.</h2><p>These visuals are generated from the completed investigation. Nothing is re-uploaded or re-analyzed.</p><div className="artifactActions"><button className="exportBtn" onClick={()=>downloadXlsx(`${datasetName||"gamur"}-visual-data`,[["Metric","Value"],...rels.slice(0,20).map(r=>[`${r.x} ↔ ${r.y}`,r.r])])}>Download visual data</button></div></div><div className="chartGrid">{charts.length?charts.map((c:any,i:number)=><article className="chart" key={i}><div className="chartHead"><div><b>{c.title||`Visual ${i+1}`}</b><small>{c.type||"chart"} · {c.xKey} × {c.yKey}</small></div></div><Chart chart={c}/></article>):<div className="emptyState">Gamur has no chart payload for this analysis yet.</div>}</div><section className="artifactSection"><div className="sectionHead"><div><span className="sectionTag">RELATIONSHIPS</span><h2>Strongest measured relationships</h2></div></div><div className="relationshipList">{rels.slice(0,12).map((r:any,i:number)=><button key={i} onClick={()=>onSelect(r)}><span>{r.x}</span><div className="bar"><i style={{width:`${Math.min(100,Math.abs(r.r)*100)}%`}}/></div><b>{Number(r.r).toFixed(2)}</b><span>{r.y}</span></button>)}</div></section></div>;
 if(tab==="statistics") return <div className="artifactView"><div className="artifactHero"><span className="sectionTag">STATISTICS</span><h2>The statistical profile of your dataset.</h2><p>Core descriptive statistics, variation, relationships, and outlier screening from the completed analysis.</p><button className="exportBtn" onClick={()=>downloadXlsx(`${datasetName||"gamur"}-statistics`,[["Column","Count","Mean","Min","Max","Std Dev"],...stats.map(s=>[s.column,s.count,s.mean,s.min,s.max,s.std])])}>Download statistics XLSX</button></div><div className="statsKpis"><div><span>ROWS</span><b>{result.analysis?.rows?.toLocaleString()||0}</b></div><div><span>FIELDS</span><b>{result.analysis?.columns||0}</b></div><div><span>NUMERIC</span><b>{result.analysis?.numeric_columns?.length||0}</b></div><div><span>OUTLIERS</span><b>{totalOutliers}</b></div></div><div className="statsTable">{stats.map(s=><div key={s.column}><b>{s.column}</b><span>n {s.count}</span><span>Mean {s.mean.toFixed(2)}</span><span>Min {s.min.toFixed(2)}</span><span>Max {s.max.toFixed(2)}</span><span>SD {s.std.toFixed(2)}</span></div>)}</div><section className="artifactSection"><div className="sectionHead"><div><span className="sectionTag">OUTLIERS</span><h2>Where values need attention</h2></div></div><div className="artifactList">{outliers.length?outliers.map((o:any)=><button key={o.column} onClick={()=>onSelect(o)}><b>{o.column}</b><span>{o.count} flagged · {(o.rate*100).toFixed(1)}%</span><i>→</i></button>):<p className="muted">No outlier screening results were returned.</p>}</div></section></div>;
 if(tab==="dashboard") return <div className="artifactView"><div className="artifactHero"><span className="sectionTag">EXECUTIVE DASHBOARD</span><h2>One view of what matters.</h2><p>Gamur's dashboard is assembled from the same evidence used in the investigation.</p></div><div className="dashboardGrid"><div className="dashboardCard"><span>OBSERVATIONS</span><b>{result.analysis?.rows?.toLocaleString()||0}</b><small>{result.analysis?.columns||0} fields</small></div><div className="dashboardCard"><span>NUMERIC FIELDS</span><b>{result.analysis?.numeric_columns?.length||0}</b><small>measured variables</small></div><div className="dashboardCard"><span>OUTLIERS</span><b>{totalOutliers}</b><small>IQR screening flags</small></div><div className="dashboardCard"><span>TARGET</span><b>{target||"—"}</b><small>analysis focus</small></div></div><div className="dashboardGrid wide">{rels.slice(0,3).map((r:any,i:number)=><button className="dashboardFinding" key={i} onClick={()=>onSelect(r)}><span>RELATIONSHIP</span><h3>{r.x} ↔ {r.y}</h3><b>r = {Number(r.r).toFixed(2)}</b><small>{r.strength||"Measured association"}</small></button>)}</div><div className="chartGrid">{charts.slice(0,4).map((c:any,i:number)=><article className="chart" key={i}><div className="chartHead"><b>{c.title}</b></div><Chart chart={c}/></article>)}</div><section className="artifactSection"><span className="sectionTag">NEXT QUESTIONS</span><h2>What to investigate next</h2><div className="questionGrid">{questions.slice(0,4).map((q:any,i:number)=><button className="question" key={i} onClick={()=>onSelect(q)}><span className="qNum">{String(i+1).padStart(2,"0")}</span><div><b>{q.question}</b><small>{q.answer}</small></div><span>→</span></button>)}</div></section></div>;
 if(tab==="forecast") return <div className="artifactView"><div className="artifactHero"><span className="sectionTag">FORECAST</span><h2>Forward-looking analysis, only when the data supports it.</h2><p>Gamur checks the completed dataset for a usable time dimension before forecasting. It will not manufacture a forecast from cross-sectional data.</p></div><div className="forecastPanel"><div><span>FORECAST STATUS</span><b>{result.forecasting?.status||"Not generated"}</b></div><div><span>NUMERIC SERIES</span><b>{result.forecasting?.numeric_series?.length||0}</b></div></div>{result.forecasting?.status&&result.forecasting.status.toLowerCase().includes("ready")?<div className="emptyState">A forecasting-ready series was detected. The next backend step is to generate horizon values and confidence intervals from the selected time series.</div>:<div className="emptyState">This saved analysis does not contain a generated forecast. That is intentional when no reliable time series is available.</div>}</div>;
 if(tab==="report") return <div className="artifactView"><div className="artifactHero"><span className="sectionTag">REPORT</span><h2>{result.report?.title||`Gamur analysis — ${datasetName||"Dataset"}`}</h2><p>Professional evidence-led report assembled from the completed investigation.</p><div className="artifactActions"><button onClick={()=>window.print()}>Print / Save as PDF</button></div></div><article className="reportPaper"><h2>Executive summary</h2><p>{result.insights||"Gamur found measurable patterns in the dataset."}</p><h2>Key evidence</h2>{rels.slice(0,8).map((r:any,i:number)=><div className="reportFinding" key={i}><b>{r.x} ↔ {r.y}</b><span>Correlation r = {Number(r.r).toFixed(2)} · {r.strength||"Measured association"}</span></div>)}<h2>Questions answered</h2>{questions.map((q:any,i:number)=><div className="reportQuestion" key={i}><b>{q.question}</b><p>{q.answer}</p></div>)}<h2>Limitations</h2><p>Correlation and computed patterns describe the observed data; they do not by themselves establish causation or guarantee future outcomes.</p></article></div>;
 return <div className="artifactView"><div className="artifactHero"><span className="sectionTag">SLIDES</span><h2>Presentation-ready story from the same analysis.</h2><p>Gamur turns the completed evidence into a concise slide narrative. Export to native PowerPoint can be added without changing the analysis engine.</p><div className="artifactActions"><button onClick={()=>window.print()}>Print / Save slides as PDF</button></div></div><div className="slideDeck"><article className="slide"><span>01 · EXECUTIVE</span><h2>{datasetName||"Dataset"}</h2><p>{result.insights||"Evidence-led analysis of the uploaded dataset."}</p></article><article className="slide"><span>02 · KEY FINDINGS</span><h2>What matters most</h2>{rels.slice(0,4).map((r:any,i:number)=><p key={i}><b>{r.x} ↔ {r.y}</b> — r {Number(r.r).toFixed(2)}</p>)}</article><article className="slide"><span>03 · QUESTIONS</span><h2>What should we investigate?</h2>{questions.slice(0,5).map((q:any,i:number)=><p key={i}>{i+1}. {q.question}</p>)}</article></div></div>;
}
