"use client";
import {useMemo,useState} from "react";
import * as XLSX from "xlsx-js-style";
import type {IntelligenceResult} from "../../lib/api";

type Props={tab:string;result:IntelligenceResult;datasetName?:string;onSelect:(value:any)=>void};
type AnyVisual=any;

const navy="17201b", green="1f6b4f", pale="eef5f0", ink="17201b", muted="68736b", border="d8e0da";
function styledWorkbook(sheets:Array<{name:string;rows:any[][];widths?:number[]}>){
 const wb=XLSX.utils.book_new();
 sheets.forEach(({name,rows,widths})=>{
  const ws=XLSX.utils.aoa_to_sheet(rows);
  ws["!freeze"]={xSplit:0,ySplit:1};
  ws["!cols"]=(widths||rows[0]?.map((_:any,i:number)=>Math.min(32,Math.max(12,...rows.slice(0,20).map(r=>String(r[i]??"").length+2)))).map((w:number)=>({wch:w}));
  const range=XLSX.utils.decode_range(ws["!ref"]||"A1:A1");
  for(let c=range.s.c;c<=range.e.c;c++){const cell=ws[XLSX.utils.encode_cell({r:0,c})];if(cell)cell.s={font:{bold:true,color:"FFFFFF",sz:11},fill:{fgColor:{rgb:navy}},alignment:{vertical:"center"}}}
  for(let r=1;r<=range.e.r;r++)for(let c=0;c<=range.e.c;c++){const cell=ws[XLSX.utils.encode_cell({r,c})];if(cell)cell.s={fill:{fgColor:{rgb:r%2?"FFFFFF":"F4F7F4"}},border:{bottom:{style:"thin",color:{rgb:"E1E7E2"}}},alignment:{vertical:"center"}}}
  XLSX.utils.book_append_sheet(wb,ws,name.slice(0,31));
 });
 return wb;
}
function exportStats(name:string,result:IntelligenceResult){
 const a=result.analysis||{} as any,stats=a.summary||[],cats=a.categorical_summary||[],rels=a.relationships||[],outs=a.outliers||[];
 const wb=styledWorkbook([
  {name:"Overview",rows:[["Gamur Statistical Analysis"],["Dataset",name],["Observations",a.rows||0],["Fields",a.columns||0],["Numeric fields",(a.numeric_columns||[]).length],["Target",a.target||""]],widths:[28,28]},
  {name:"Descriptive Statistics",rows:[["Variable","N","Missing","Unique","Mean","Median","Std. Dev.","Variance","Min","Q1","Q3","Max","Range","IQR","P05","P10","P90","P95"],...stats.map((s:any)=>[s.column,s.count,s.missing||0,s.unique||0,s.mean,s.median,s.std,s.variance,s.min,s.q1,s.q3,s.max,s.range,s.iqr,s.p05,s.p10,s.p90,s.p95])],widths:[28,10,10,10,14,14,14,14,14,14,14,14,14,14,14,14,14,14]},
  {name:"Pivot Summary",rows:[["Variable","Mean","Median","Min","Max","Std. Dev.","Outlier Count"],...stats.map((s:any)=>[s.column,s.mean,s.median,s.min,s.max,s.std,outs.find((o:any)=>o.column===s.column)?.count||0])],widths:[28,14,14,14,14,14,16]},
  {name:"Categories",rows:[["Field","Value","Count","Share"],...cats.flatMap((c:any)=>c.top_values.map((v:any)=>[c.column,v.value,v.count,v.share]))],widths:[28,30,14,14]},
  {name:"Correlations",rows:[["Variable A","Variable B","Correlation","Strength"],...rels.map((r:any)=>[r.x,r.y,r.r,r.strength])],widths:[28,28,16,18]},
  {name:"Outliers",rows:[["Variable","Flagged Rows","Rate","Lower Bound","Upper Bound"],...outs.map((o:any)=>[o.column,o.count,o.rate,o.lower,o.upper])],widths:[28,16,14,18,18]},
  {name:"Data Quality",rows:[["Metric","Value"],["Rows after cleaning",result.cleaning?.rows_after||a.rows||0],["Cleaning actions",result.cleaning?.changes?.length||0],["Date fields detected",a.date_columns?.length||0],["Numeric fields",(a.numeric_columns||[]).length],["Categorical fields",(a.categorical_columns||[]).length]],widths:[30,24]}
 ]);
 XLSX.writeFile(wb,`${name||"gamur"}-visual-statistics.xlsx`);
}
function exportForecast(name:string,result:IntelligenceResult,horizon:number){
 const f=result.forecasting||{} as any;
 const rows=[["Gamur Forecast Workbook"],["Forecast status",f.status||"Not forecastable"],["Target",f.target||""],["Date field",f.date_column||""],["Horizon (years)",horizon],["Frequency",f.frequency||""],["Historical period",`${f.history_start||""} → ${f.history_end||""}`],["Method","Forecast engine uses validated time-series methods; model details are recorded with the forecast."]];
 const wb=styledWorkbook([{name:"Forecast",rows,widths:[30,55]},{name:"Accuracy",rows:[["Metric","Value"],["Status",f.status||"not_forecastable"],["History years",f.history_years||""],["Observations",f.observations||0]],widths:[24,28]},{name:"Assumptions",rows:[["Item","Value"],["Minimum horizon","1 year"],["Maximum horizon","10 years"],["Forecastability",f.reason||""],["Caution","Forecasts are estimates and should be validated against historical holdout performance."]],widths:[24,70]}]);
 XLSX.writeFile(wb,`${name||"gamur"}-forecast-${horizon}y.xlsx`);
}
function downloadReportData(name:string,result:IntelligenceResult){const a=result.analysis||{} as any;const wb=styledWorkbook([{name:"Report Evidence",rows:[["Finding","Correlation","Strength"],...(a.relationships||[]).map((r:any)=>[`${r.x} ↔ ${r.y}`,r.r,r.strength])],widths:[44,18,18]},{name:"Questions",rows:[["Question","Answer"],...(result.questions||[]).map((q:any)=>[q.question,q.answer])],widths:[50,100]}]);XLSX.writeFile(wb,`${name||"gamur"}-report-evidence.xlsx`)}

function LineChart({v}:{v:AnyVisual}){const d=v.data||[];if(!d.length)return <div className="visualEmpty">No data</div>;const ys=d.map((p:any)=>Number(p[v.yKey])),min=Math.min(...ys),max=Math.max(...ys),range=Math.max(1,max-min),pts=d.map((p:any,i:number)=>`${36+(i/Math.max(1,d.length-1))*500},${188-((Number(p[v.yKey])-min)/range)*150}`).join(" ");return <svg viewBox="0 0 560 220" className="svgChart"><line x1="36" y1="18" x2="36" y2="188"/><line x1="36" y1="188" x2="540" y2="188"/><polyline fill="none" stroke="currentColor" strokeWidth="3" points={pts}/>{d.filter((_:any,i:number)=>i%Math.max(1,Math.floor(d.length/12))===0).map((p:any,i:number)=><circle key={i} cx={36+(d.indexOf(p)/Math.max(1,d.length-1))*500} cy={188-((Number(p[v.yKey])-min)/range)*150} r="3"><title>{`${v.yKey}: ${Number(p[v.yKey]).toFixed(2)}`}</title></circle>)}<text x="40" y="207">{v.xKey}</text><text x="430" y="207">{v.yKey}</text></svg>}
function BarChart({v}:{v:AnyVisual}){const d=(v.data||[]).slice(0,14),max=Math.max(1,...d.map((p:any)=>Number(p[v.yKey])));return <svg viewBox="0 0 620 280" className="svgChart">{d.map((p:any,i:number)=>{const y=12+i*18,w=500*Number(p[v.yKey])/max;return <g key={i}><text x="4" y={y+11} fontSize="9">{String(p[v.xKey]).slice(0,22)}</text><rect x="120" y={y} width={w} height="11" rx="3"/><text x={125+w} y={y+10} fontSize="9">{p[v.yKey]}</text></g>})}</svg>}
function Scatter({v}:{v:AnyVisual}){const d=v.data||[],xs=d.map((p:any)=>Number(p[v.xKey])),ys=d.map((p:any)=>Number(p[v.yKey])),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),xr=Math.max(1,xmax-xmin),yr=Math.max(1,ymax-ymin);return <svg viewBox="0 0 560 220" className="svgChart"><line x1="36" y1="18" x2="36" y2="188"/><line x1="36" y1="188" x2="540" y2="188"/>{d.slice(0,240).map((p:any,i:number)=><circle key={i} cx={36+((Number(p[v.xKey])-xmin)/xr)*500} cy={188-((Number(p[v.yKey])-ymin)/yr)*150} r="3"><title>{`${v.xKey}: ${Number(p[v.xKey]).toFixed(2)} · ${v.yKey}: ${Number(p[v.yKey]).toFixed(2)}`}</title></circle>)}<text x="40" y="207">{v.xKey}</text><text x="420" y="207">{v.yKey} · r {Number(v.r||0).toFixed(2)}</text></svg>}
function Histogram({v}:{v:AnyVisual}){return <BarChart v={v}/>} 
function Box({v}:{v:AnyVisual}){const vals=[v.min,v.q1,v.median,v.q3,v.max],min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),x=(n:number)=>50+((n-min)/range)*480;return <svg viewBox="0 0 560 150" className="svgChart"><line x1={x(v.min)} y1="75" x2={x(v.max)} y2="75"/><line x1={x(v.min)} y1="60" x2={x(v.min)} y2="90"/><line x1={x(v.max)} y1="60" x2={x(v.max)} y2="90"/><rect x={x(v.q1)} y="48" width={Math.max(2,x(v.q3)-x(v.q1))} height="54" rx="5"/><line x1={x(v.median)} y1="48" x2={x(v.median)} y2="102" strokeWidth="4"/><text x="50" y="130">{v.min.toFixed(1)}</text><text x="245" y="130">Median {v.median.toFixed(1)}</text><text x="485" y="130">{v.max.toFixed(1)}</text></svg>}
function Heatmap({v}:{v:AnyVisual}){const cols=v.columns||[],m=v.matrix||[],n=Math.max(1,cols.length);return <div className="heatmap" style={{gridTemplateColumns:`repeat(${n},minmax(30px,1fr))`}}>{m.flatMap((row:any[],i:number)=>row.map((val:any,j:number)=><div key={`${i}-${j}`} title={`${cols[i]} × ${cols[j]}: ${val==null?"":Number(val).toFixed(2)}`} className="heatCell" style={{opacity:Math.min(1,.15+Math.abs(Number(val||0))*.85)}}>{Math.abs(Number(val||0))>.75?Number(val).toFixed(1):""}</div>))}</div>}
function Visual({v}:{v:AnyVisual}){if(v.type==="bar"||v.type==="histogram")return <BarChart v={v}/>;if(v.type==="scatter")return <Scatter v={v}/>;if(v.type==="box")return <Box v={v}/>;if(v.type==="heatmap")return <Heatmap v={v}/>;return <LineChart v={v}/>}
function MiniKpi({label,value,sub}:{label:string;value:any;sub?:string}){return <div className="miniKpi"><span>{label}</span><b>{value}</b>{sub&&<small>{sub}</small>}</div>}

export default function ArtifactViews({tab,result,datasetName,onSelect}:Props){
 const [horizon,setHorizon]=useState(1),[visualFilter,setVisualFilter]=useState("all"),[dashSearch,setDashSearch]=useState("");
 const a=result.analysis||{} as any,stats=a.summary||[],rels=a.relationships||result.visualization?.relationships||[],outs=a.outliers||[],questions=result.questions||[],visuals=(result.visualization?.visuals||result.visualization?.charts||[]) as AnyVisual[];
 const filtered=visualFilter==="all"?visuals:visuals.filter(v=>v.category===visualFilter);
 const totalOutliers=useMemo(()=>outs.reduce((n:number,x:any)=>n+x.count,0),[outs]);
 const matchingRels=rels.filter((r:any)=>`${r.x} ${r.y}`.toLowerCase().includes(dashSearch.toLowerCase()));
 const title=datasetName||"Dataset";
 if(tab==="visualize"||tab==="statistics")return <div className="artifactView">
  <section className="artifactHero visualHero"><div><span className="sectionTag">{tab==="visualize"?"VISUALIZATION + STATISTICS":"STATISTICS + PIVOT ANALYSIS"}</span><h2>{tab==="visualize"?"See the data from every useful angle.":"Statistics that actually look like statistics."}</h2><p>{tab==="visualize"?"Gamur automatically chooses the useful visual language for this dataset: trends, distributions, comparisons, relationships, rankings, anomalies and correlation structure. There is no five-chart limit.":"A proper statistical workbook: descriptive statistics, frequencies, pivot-style summaries, correlations, outliers and data quality—designed as one decision-ready file."}</p></div><div className="heroBadge"><b>{visuals.length}</b><span>visual evidence views</span></div><div className="artifactActions"><button onClick={()=>exportStats(title,result)}>Download beautiful Excel</button><button onClick={()=>window.print()}>Save PDF</button></div></section>
  <section className="statKpiRow"><MiniKpi label="OBSERVATIONS" value={(a.rows||0).toLocaleString()}/><MiniKpi label="NUMERIC" value={(a.numeric_columns||[]).length}/><MiniKpi label="CATEGORICAL" value={(a.categorical_columns||[]).length}/><MiniKpi label="OUTLIER FLAGS" value={totalOutliers}/><MiniKpi label="TARGET" value={a.target||"—"}/></section>
  {tab==="statistics"&&<><section className="properTableBlock"><div className="sectionHead"><div><span className="sectionTag">DESCRIPTIVE STATISTICS</span><h2>Analyst table</h2></div><span className="muted">N · missing · unique · mean · median · SD · variance · quartiles · range</span></div><div className="wideTable"><div className="wideRow wideHeader">{["Variable","N","Missing","Mean","Median","Std Dev","Min","Q1","Q3","Max","Range","IQR"].map(x=><b key={x}>{x}</b>)}</div>{stats.map((s:any)=><div className="wideRow" key={s.column}><b>{s.column}</b><span>{s.count}</span><span>{s.missing||0}</span><span>{Number(s.mean).toFixed(3)}</span><span>{Number(s.median).toFixed(3)}</span><span>{Number(s.std).toFixed(3)}</span><span>{Number(s.min).toFixed(3)}</span><span>{Number(s.q1).toFixed(3)}</span><span>{Number(s.q3).toFixed(3)}</span><span>{Number(s.max).toFixed(3)}</span><span>{Number(s.range).toFixed(3)}</span><span>{Number(s.iqr).toFixed(3)}</span></div>)}</div></section><section className="twoCol"><div className="properTableBlock"><div className="sectionHead"><div><span className="sectionTag">PIVOT-STYLE SUMMARY</span><h2>Numbers → quick comparison</h2></div></div><div className="pivotGrid">{stats.slice(0,10).map((s:any)=><button key={s.column} onClick={()=>onSelect(s)}><b>{s.column}</b><span>Mean {Number(s.mean).toFixed(2)}</span><span>Median {Number(s.median).toFixed(2)}</span><span>Range {Number(s.range).toFixed(2)}</span></button>)}</div></div><div className="properTableBlock"><div className="sectionHead"><div><span className="sectionTag">HUMAN-READABLE FINDINGS</span><h2>What the numbers mean</h2></div></div>{questions.slice(0,6).map((q:any)=><button className="findingLine" key={q.question} onClick={()=>onSelect(q)}><b>{q.question}</b><span>{q.answer}</span></button>)}</div></section></>}
  <section className="visualToolbar"><div><span className="sectionTag">VISUAL LIBRARY</span><h2>{tab==="visualize"?"Best visual evidence":"Charts that support the statistics"}</h2></div><div className="visualFilters">{["all","trend","distribution","relationship","comparison"].map(f=><button key={f} className={visualFilter===f?"active":""} onClick={()=>setVisualFilter(f)}>{f}</button>)}</div></section>
  <section className="visualMasonry">{filtered.map((v,i)=><article className={`visualCard ${v.type==="heatmap"?"full":v.type==="box"?"compact":""}`} key={i}><div className="visualCardHead"><div><span>{v.category||"evidence"}</span><h3>{v.title||`Visual ${i+1}`}</h3></div>{v.r!==undefined&&<b>r {Number(v.r).toFixed(3)}</b>}</div><Visual v={v}/><div className="visualCaption">{v.type==="histogram"?"Distribution shows where observations concentrate.":v.type==="box"?`${v.outlierCount||0} flagged outlier observations.`:v.type==="heatmap"?"Correlation strength across numeric variables.":v.type==="scatter"?"Relationship evidence; association does not establish causation.":"Trend or ordered-observation view for pattern recognition."}</div></article>)}</section>
 </div>;
 if(tab==="dashboard")return <div className="dashboardPage"><header className="dashboardHeader"><div><span className="sectionTag">INTERACTIVE ANALYTICS DASHBOARD</span><h1>{title}</h1><p>Explore the completed Gamur investigation as a live analytical workspace. Hover visuals for values and click findings to inspect evidence.</p></div><div className="dashboardControls"><input value={dashSearch} onChange={e=>setDashSearch(e.target.value)} placeholder="Filter findings…"/><button onClick={()=>window.print()}>Print dashboard</button></div></header><section className="dashboardKpis"><MiniKpi label="RECORDS" value={(a.rows||0).toLocaleString()} sub="analyzed"/><MiniKpi label="FIELDS" value={a.columns||0}/><MiniKpi label="STRONGEST RELATION" value={rels[0]?Number(rels[0].r).toFixed(2):"—"} sub={rels[0]?.x||""}/><MiniKpi label="ANOMALIES" value={totalOutliers} sub="IQR flags"/><MiniKpi label="QUESTIONS" value={questions.length} sub="answered"/></section><section className="dashboardGridNew"><article className="dashPanel heroPanel"><div className="dashPanelTitle"><div><span className="sectionTag">PRIMARY VISUALS</span><h2>What changed or stands out</h2></div></div>{visuals.filter(v=>v.type==="line").slice(0,2).map((v,i)=><div className="dashVisual" key={i}><b>{v.title}</b><Visual v={v}/></div>)}</article><article className="dashPanel"><div className="dashPanelTitle"><div><span className="sectionTag">TOP RELATIONSHIPS</span><h2>What moves together</h2></div></div>{matchingRels.slice(0,7).map((r:any,i:number)=><button className="dashRelation" key={i} onClick={()=>onSelect(r)}><span>{r.x}</span><div><i style={{width:`${Math.min(100,Math.abs(r.r)*100)}%`}}/></div><b>{Number(r.r).toFixed(2)}</b><span>{r.y}</span></button>)}</article><article className="dashPanel"><div className="dashPanelTitle"><div><span className="sectionTag">DISTRIBUTIONS</span><h2>Where values sit</h2></div></div>{visuals.filter(v=>v.type==="histogram").slice(0,4).map((v,i)=><div className="dashMiniVisual" key={i}><b>{v.title}</b><Visual v={v}/></div>)}</article><article className="dashPanel"><div className="dashPanelTitle"><div><span className="sectionTag">EXCEPTIONS</span><h2>Review these</h2></div></div>{outs.slice(0,8).map((o:any)=><button className="exception" key={o.column} onClick={()=>onSelect(o)}><b>{o.column}</b><span>{o.count} flags</span><strong>{(o.rate*100).toFixed(1)}%</strong></button>)}{!outs.length&&<p className="muted">No exceptions detected.</p>}</article></section><section className="dashboardFooter"><span>Evidence source: completed Gamur investigation</span><span>Click any finding to inspect its evidence</span></section></div>;
 if(tab==="forecast")return <div className="artifactView"><section className="artifactHero"><div><span className="sectionTag">FORECAST WORKSPACE</span><h2>Forecast only when the data earns it.</h2><p>Gamur checks for a real time dimension, a numeric target and enough historical observations before forecasting. Choose the horizon below; one year is the minimum and ten years is the maximum.</p></div><div className="forecastSetup"><label>Forecast horizon</label><select value={horizon} onChange={e=>setHorizon(Number(e.target.value))}>{Array.from({length:10},(_,i)=><option key={i+1} value={i+1}>{i+1} year{i?"s":""}</option>)}</select><button onClick={()=>exportForecast(title,result,horizon)}>Download forecast Excel</button></div></section><section className="forecastStatus"><MiniKpi label="STATUS" value={result.forecasting?.status||"—"}/><MiniKpi label="TARGET" value={result.forecasting?.target||a.target||"—"}/><MiniKpi label="TIME FIELD" value={result.forecasting?.date_column||"—"}/><MiniKpi label="HISTORY" value={result.forecasting?.history_years?`${result.forecasting.history_years}y`:"—"}/><MiniKpi label="FREQUENCY" value={result.forecasting?.frequency||"—"}/></section><article className="forecastPaper"><span className="sectionTag">FORECAST DECISION</span><h2>{result.forecasting?.status==="forecastable"?`Forecast can be generated for ${horizon} year${horizon>1?"s":""}.`:"This dataset is not currently forecastable."}</h2><p>{result.forecasting?.reason||"Gamur needs a usable date field, numeric target and sufficient distinct observations."}</p>{result.forecasting?.status==="forecastable"&&<div className="forecastSteps"><div><b>01</b><span>Validate time series</span></div><div><b>02</b><span>Back-test candidate models</span></div><div><b>03</b><span>Forecast selected horizon</span></div><div><b>04</b><span>Report uncertainty + accuracy</span></div></div>}</article></div>;
 if(tab==="report")return <div className="reportWorkspace"><header className="reportHeader"><div><span className="sectionTag">BUSINESS REPORT</span><h1>{result.report?.title||`Data Intelligence Report — ${title}`}</h1><p>Decision-ready narrative built from the same evidence used by Analytics, Visualization + Statistics, Dashboard and Forecast.</p></div><div className="reportActions"><button onClick={()=>window.print()}>Save PDF</button><button onClick={()=>downloadReportData(title,result)}>Evidence Excel</button></div></header><article className="reportPaperNew"><section><span className="sectionTag">01 · EXECUTIVE SUMMARY</span><h2>What management should know</h2><p>{result.insights||"Gamur found measurable patterns in the completed investigation."}</p></section><section><span className="sectionTag">02 · DATA PROFILE</span><div className="reportMetrics"><MiniKpi label="OBSERVATIONS" value={a.rows||0}/><MiniKpi label="FIELDS" value={a.columns||0}/><MiniKpi label="NUMERIC" value={(a.numeric_columns||[]).length}/><MiniKpi label="ANOMALIES" value={totalOutliers}/></div></section><section><span className="sectionTag">03 · KEY EVIDENCE</span>{rels.slice(0,8).map((r:any,i:number)=><div className="reportEvidence" key={i}><b>{r.x} ↔ {r.y}</b><strong>r {Number(r.r).toFixed(3)}</strong><span>{r.strength||"Measured association"}. This is evidence of association, not proof of causation.</span></div>)}</section><section><span className="sectionTag">04 · QUESTIONS ANSWERED</span>{questions.map((q:any,i:number)=><div className="reportQ" key={i}><b>{String(i+1).padStart(2,"0")} · {q.question}</b><p>{q.answer}</p></div>)}</section><section><span className="sectionTag">05 · LIMITATIONS</span><p>Gamur reports observed evidence and clearly separates association from causation. Forecasts require suitable time-series structure, validation and uncertainty reporting.</p></section></article></div>;
 return <div className="artifactView"><section className="artifactHero"><span className="sectionTag">WORKSPACE</span><h2>Choose an analytical view from the top navigation.</h2><p>Slides are intentionally removed from the current Gamur build. The core workspaces are Analytics, Visualization + Statistics, Dashboard, Forecast and Report.</p></section></div>;
}
