"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import type {ElementType} from "react";
import * as XLSX from "xlsx";
import {createSupabaseBrowserClient} from "../../lib/supabase-browser";
import {createProject,getProjects,uploadDataset,createDatasetVersion,runIntelligence,getHistory,createHistory,renameHistory,deleteHistory,askData,type Project,type Dataset,type IntelligenceResult,type HistoryItem} from "../../lib/api";

type Tab="analyze"|"visualize"|"statistics"|"dashboard"|"forecast"|"report"|"powerpoint";
const tabs:[Tab,string][]=[["analyze","Analyze"],["visualize","Visualize"],["statistics","Statistics"],["dashboard","Dashboard"],["forecast","Forecast"],["report","Report"],["powerpoint","Slides"]];

function Markdown({text}:{text:string}){const lines=text.split(/\r?\n/);return <div className="markdown">{lines.map((line,i)=>{const s=line.trim();if(!s)return <div className="mdSpace" key={i}/>;const m=s.match(/^(#{1,4})\s+(.*)$/);if(m){const C=("h"+Math.min(4,m[1].length)) as ElementType;return <C key={i}>{inlineMd(m[2])}</C>}if(/^[-*]\s+/.test(s))return <div className="mdBullet" key={i}>• <span>{inlineMd(s.replace(/^[-*]\s+/,""))}</span></div>;return <p key={i}>{inlineMd(s)}</p>})}</div>}
function inlineMd(s:string){const parts=s.split(/(\*\*[^*]+\*\*)/g);return parts.map((p,i)=>p.startsWith("**")&&p.endsWith("**")?<strong key={i}>{p.slice(2,-2)}</strong>:p)}
function Chart({chart}:{chart:any}){const d=(chart?.data||[]).filter((p:any)=>Number.isFinite(Number(p[chart.xKey]))&&Number.isFinite(Number(p[chart.yKey])));if(!d.length)return <div className="chartEmpty">No visual evidence available</div>;const ys=d.map((p:any)=>Number(p[chart.yKey]));const ymin=Math.min(...ys),ymax=Math.max(...ys),range=Math.max(1,ymax-ymin);return <div className="chartCanvas"><svg viewBox="0 0 640 230" role="img" aria-label={chart.title}><line x1="48" y1="15" x2="48" y2="200"/><line x1="48" y1="200" x2="625" y2="200"/><line x1="48" y1="108" x2="625" y2="108"/>{chart.type==="scatter"?d.slice(0,180).map((p:any,i:number)=><circle key={i} cx={55+(i/Math.max(1,d.length-1))*565} cy={195-((Number(p[chart.yKey])-ymin)/range)*175} r="3"/>):<polyline fill="none" stroke="currentColor" strokeWidth="3" points={d.map((p:any,i:number)=>`${55+(i/Math.max(1,d.length-1))*565},${195-((Number(p[chart.yKey])-ymin)/range)*175}`).join(" ")}/>}</svg><div className="chartAxes"><span>{chart.xKey}</span><span>{chart.yKey} · {ymin.toFixed(1)}–{ymax.toFixed(1)}</span></div></div>}

export default function Workspace(){
 const[tab,setTab]=useState<Tab>("analyze"),[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[dataset,setDataset]=useState<Dataset|null>(null),[sourceFile,setSourceFile]=useState<File|null>(null),[prompt,setPrompt]=useState(""),[result,setResult]=useState<IntelligenceResult|null>(null),[history,setHistory]=useState<HistoryItem[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<any>(null),[chat,setChat]=useState<{role:string;text:string}[]>([]),[profileOpen,setProfileOpen]=useState(false),[renameId,setRenameId]=useState<string|null>(null),[renameValue,setRenameValue]=useState(""),[deleteId,setDeleteId]=useState<string|null>(null);