"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import * as XLSX from "xlsx";
import {createSupabaseBrowserClient} from "../../lib/supabase-browser";
import {createProject,getProjects,uploadDataset,createDatasetVersion,runIntelligence,getHistory,createHistory,renameHistory,deleteHistory,askData,type Project,type Dataset,type IntelligenceResult,type HistoryItem} from "../../lib/api";

type Tab="analyze"|"visualize"|"statistics"|"dashboard"|"forecast"|"report"|"powerpoint";
const tabs:[Tab,string][]=[["analyze","Analyze"],["visualize","Visualize"],["statistics","Statistics"],["dashboard","Dashboard"],["forecast","Forecast"],["report","Report"],["powerpoint","Slides"]];

function Markdown({text}:{text:string}){const lines=text.split(/\r?\n/);return <div className="markdown">{lines.map((line,i)=>{const s=line.trim();if(!s)return <div className="mdSpace" key={i}/>;const m=s.match(/^(#{1,4})\s+(.*)$/);if(m){const C=("h"+Math.min(4,m[1].length)) as keyof JSX.IntrinsicElements;return <C key={i}>{inlineMd(m[2])}</C>}if(/^[-*]\s+/.test(s))return <div className="mdBullet" key={i}>• <span>{inlineMd(s.replace(/^[-*]\s+/,""))}</span></div>;return <p key={i}>{inlineMd(s)}</p>})}</div>}
function inlineMd(s:string){const parts=s.split(/(\*\*[^*]+\*\*)/g);return parts.map((p,i)=>p.startsWith("**")&&p.endsWith("**")?<strong key={i}>{p.slice(2,-2)}</strong>:p)}
function Chart({chart}:{chart:any}){const d=(chart?.data||[]).filter((p:any)=>Number.isFinite(Number(p[chart.xKey]))&&Number.isFinite(Number(p[chart.yKey])));if(!d.length)return <div className="chartEmpty">No visual evidence available</div>;const ys=d.map((p:any)=>Number(p[chart.yKey]));const ymin=Math.min(...ys),ymax=Math.max(...ys),range=Math.max(1,ymax-ymin);return <div className="chartCanvas"><svg viewBox="0 0 640 230" role="img" aria-label={chart.title}><line x1="48" y1="15" x2="48" y2="200"/><line x1="48" y1="200" x2="625" y2="200"/><line x1="48" y1="108" x2="625" y2="108"/>{chart.type==="scatter"?d.slice(0,180).map((p:any,i:number)=><circle key={i} cx={55+(i/Math.max(1,d.length-1))*565} cy={195-((Number(p[chart.yKey])-ymin)/range)*175} r="3"/>):<polyline fill="none" stroke="currentColor" strokeWidth="3" points={d.map((p:any,i:number)=>`${55+(i/Math.max(1,d.length-1))*565},${195-((Number(p[chart.yKey])-ymin)/range)*175}`).join(" ")}/>}</svg><div className="chartAxes"><span>{chart.xKey}</span><span>{chart.yKey} · {ymin.toFixed(1)}–{ymax.toFixed(1)}</span></div></div>}

export default function Workspace(){
 const[tab,setTab]=useState<Tab>("analyze"),[projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[dataset,setDataset]=useState<Dataset|null>(null),[sourceFile,setSourceFile]=useState<File|null>(null),[prompt,setPrompt]=useState(""),[result,setResult]=useState<IntelligenceResult|null>(null),[history,setHistory]=useState<HistoryItem[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<any>(null),[chat,setChat]=useState<{role:string;text:string}[]>([]),[profileOpen,setProfileOpen]=useState(false),[renameId,setRenameId]=useState<string|null>(null),[renameValue,setRenameValue]=useState(""),[deleteId,setDeleteId]=useState<string|null>(null);
 const ref=useRef<HTMLInputElement>(null);const sb=createSupabaseBrowserClient();
 useEffect(()=>{if(!sb)return;sb.auth.getSession().then(async({data})=>{if(!data.session)return;try{const[p,h]=await Promise.all([getProjects(data.session.access_token),getHistory(data.session.access_token)]);setProjects(p);setHistory(h);if(p[0])setProject(p[0])}catch(e){setError(e instanceof Error?e.message:"Could not load Gamur.")}})},[]);
 const token=async()=>{const s=await sb?.auth.getSession();return s?.data.session?.access_token||""};
 const context=useMemo(()=>{if(!result)return "";return JSON.stringify({dataset:dataset?.name,analysis:result.analysis,questions:result.questions,cleaning:result.cleaning,insights:result.insights})},[result,dataset]);
 const openHistory=(h:HistoryItem)=>{setError("");setProject(projects.find(p=>p.id===h.project_id)||null);setResult(h.result&&Object.keys(h.result).length?h.result:null);setChat([]);if(!h.result||!Object.keys(h.result).length)setError("This older analysis has no saved snapshot. Re-run it once to create one.")};
 const run=async(uploaded?:File)=>{setBusy(true);setError("");try{const t=await token();if(!t)throw Error("Please sign in first.");let p=project;if(!p){p=await createProject(t,uploaded?.name.replace(/\.(csv|xlsx)$/i,"")||"My analysis");setProject(p);setProjects(x=>[p!,...x])}let d=dataset;if(uploaded){setSourceFile(uploaded);d=await uploadDataset(t,p.id,uploaded.name.replace(/\.(csv|xlsx)$/i,""),uploaded);setDataset(d)}if(!d)throw Error("Upload a CSV or XLSX dataset first.");const stages=tab==="forecast"?["cleaning","analysis","forecasting","insights","visualization","report"]:tab==="report"||tab==="powerpoint"?["cleaning","analysis","insights","visualization","report"]:["cleaning","analysis","insights","visualization"];const r=await runIntelligence(t,p.id,d.id,prompt||"Automatically investigate this dataset comprehensively: identify important signals, anomalies, relationships, and answer key questions with evidence.",stages);setResult(r);const h=await createHistory(t,p.id,d.name||"Analysis",tab,d.id,r);setHistory(x=>[h,...x.filter(i=>i.id!==h.id)]);setPrompt("")}catch(e){setError(e instanceof Error?e.message:"Gamur could not complete the analysis.")}finally{setBusy(false)}};
 const sendChat=async()=>{if(!prompt.trim()||busy)return;const q=prompt.trim();setPrompt("");setChat(x=>[...x,{role:"user",text:q}]);try{const t=await token();const r=await askData(t,q,context);setChat(x=>[...x,{role:"assistant",text:r.answer}])}catch(e){setChat(x=>[...x,{role:"assistant",text:e instanceof Error?e.message:"Assistant unavailable."}])}};
 const deleteSaved=async()=>{if(!deleteId)return;try{const t=await token();await deleteHistory(t,deleteId);setHistory(x=>x.filter(h=>h.id!==deleteId));setDeleteId(null)}catch(e){setError(e instanceof Error?e.message:"Could not delete analysis.")}};
 const exportClean=async()=>{if(!sourceFile){setError("Re-upload the source file in this session to create a cleaned Excel export.");return}try{const buf=await sourceFile.arrayBuffer();const wb=XLSX.read(buf,{type:"array"});const ws=wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json<any[]>(ws,{header:1,defval:null,raw:true}) as any[][];if(!rows.length)throw Error("The dataset is empty.");const header=(rows.shift()||[]).map((x:any,i:number)=>String(x??`Column ${i+1}`).trim().replace(/\s+/g," ")||`Column ${i+1}`);const seen=new Map<string,number>();const uniqueHeader=header.map(h=>{const n=seen.get(h)||0;seen.set(h,n+1);return n?`${h} (${n+1})`:h});const out:any[][]=[];const keys=new Set<string>();for(const row of rows){if(!row.some(v=>v!==null&&v!==""))continue;const obj:any={};uniqueHeader.forEach((h,i)=>obj[h]=row[i]??null);const key=JSON.stringify(obj);if(keys.has(key))continue;keys.add(key);out.push(uniqueHeader.map(h=>obj[h]))}const cleaned=[uniqueHeader,...out];const sheet=XLSX.utils.aoa_to_sheet(cleaned);const outWb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(outWb,sheet,"Cleaned Data");XLSX.writeFile(outWb,`${dataset?.name||"gamur-data"}-cleaned.xlsx`);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not create cleaned Excel file.")}};
 const charts=useMemo(()=>result?.visualization?.charts||[],[result]);const rels=result?.analysis?.relationships||[];const questions=result?.questions||[];const summary=result?.analysis?.summary||[];const target=result?.analysis?.target;const topRel=rels[0];const variable=summary.length?summary.reduce((a:any,b:any)=>a.std>b.std?a:b):null;const totalOutliers=result?.analysis?.outliers?.reduce((n,x)=>n+x.count,0)||0;
 return <div className="workspace">
  <aside className="history"><div className="brand"><img src="/gamur-lockup.svg" alt="Gamur"/></div><button className="new" onClick={()=>{setResult(null);setDataset(null);setSourceFile(null);setPrompt("");setChat([]);setError("")}}>＋ New analysis</button><div className="historyTitle">RECENT ANALYSES</div>{history.length?history.map(h=><div className="historyRow" key={h.id}><button className="historyItem" onClick={()=>openHistory(h)}><span className="historyDot"/><div><b>{h.title||"Analysis"}</b><small>{new Date(h.created_at).toLocaleDateString()}</small></div></button><button className="renameBtn" title="Rename" onClick={()=>{setRenameId(h.id);setRenameValue(h.title||"")}}>•••</button><button className="deleteBtn" title="Delete" onClick={()=>setDeleteId(h.id)}>×</button></div>):<p className="empty">Your saved analyses will appear here.</p>}</aside>
  <section className="work"><header className="appHeader"><nav className="tabs">{tabs.map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav><div className="profileWrap"><button className="profile" onClick={()=>setProfileOpen(v=>!v)}>G</button>{profileOpen&&<div className="profileMenu"><b>Gamur account</b><span>Signed in</span><a href="/profile">Profile</a><a href="/settings">Settings</a><button onClick={()=>sb?.auth.signOut()}>Sign out</button></div>}</div></header>
   <main className="content"><input ref={ref} hidden type="file" accept=".csv,.xlsx" onChange={e=>{const f=e.target.files?.[0];if(f&&/\.(csv|xlsx)$/i.test(f.name))void run(f);else if(f)setError("Use CSV or XLSX files.")}}/><div className="topline"><div><span className="eyebrow">DATA INTELLIGENCE</span><h1>{dataset?.name||"Bring data to life."}</h1><p>{dataset?`${result?.analysis?.rows?.toLocaleString()||"—"} observations · ${result?.analysis?.columns||"—"} fields · automatic evidence-led investigation.`:"Upload an Excel or CSV file. Gamur investigates it automatically."}</p></div><select value={project?.id||""} onChange={e=>{setProject(projects.find(p=>p.id===e.target.value)||null);setDataset(null);setResult(null);setSourceFile(null);setChat([])}}><option value="">Project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></div>{error&&<div className="error">{error}</div>}
   {!result?<section className="landing"><div className="landingBadge">✦ AUTOMATIC INVESTIGATION</div><h2>Upload your data.<br/><em>Gamur answers.</em></h2><p>Bring in a CSV or XLSX and Gamur automatically finds the strongest signals, anomalies, relationships, and questions worth answering.</p><button className="dropzone" onClick={()=>ref.current?.click()}><span className="uploadIcon">↑</span><strong>Attach your data</strong><small>Drag and drop CSV or XLSX, or browse files</small></button><div className="featureGrid"><div><b>01</b><strong>Important signals</strong><span>What matters most</span></div><div><b>02</b><strong>Anomalies</strong><span>What needs attention</span></div><div><b>03</b><strong>Relationships</strong><span>What moves together</span></div><div><b>04</b><strong>Questions & answers</strong><span>What the data can tell you</span></div></div></section>:
   <div className="results"><section className="readout"><div className="readoutMain"><span className="sectionTag">EXECUTIVE READOUT</span><h2>What is happening?</h2><Markdown text={typeof result.insights==="string"?result.insights:"Gamur found measurable patterns in this dataset."}/><div className="evidenceLine"><span>Evidence-led</span><span>{result.analysis?.numeric_columns?.length||0} numeric fields</span><span>{target?`Target: ${target}`:"Descriptive analysis"}</span></div></div><div className="readoutSide"><span>ANALYSIS STATUS</span><b>Complete</b><small>Computed evidence saved</small></div></section>
    <div className="signalGrid"><div className="signal"><span>STRONGEST SIGNAL</span><b>{topRel?.x||"—"}</b><strong>{topRel?`r = ${topRel.r.toFixed(2)}`:"—"}</strong><small>{target?`relationship with ${target}`:"Primary relationship"}</small></div><div className="signal"><span>WIDEST VARIATION</span><b>{variable?.column||"—"}</b><strong>{variable?`SD ${variable.std.toFixed(2)}`:"—"}</strong><small>largest observed spread</small></div><div className="signal"><span>OBSERVATIONS</span><b>{result.analysis?.rows?.toLocaleString()||0}</b><strong>{result.analysis?.columns||0} fields</strong><small>after preparation</small></div><div className="signal"><span>ANOMALIES</span><b>{totalOutliers}</b><strong>outlier rows</strong><small>IQR screening</small></div></div>
    <section className="section"><div className="sectionHead"><div><span className="sectionTag">DISCOVERIES</span><h2>What Gamur found</h2></div><span className="muted">Click a finding to inspect its evidence</span></div><div className="discoveryGrid">{rels.slice(0,4).map((r:any,i:number)=><button className="discovery" key={i} onClick={()=>setSelected(r)}><div className="discoveryTop"><span className="pill">{r.strength}</span><b>r {r.r.toFixed(2)}</b></div><h3>{r.x} <i>→</i> {r.y}</h3><p>{Math.abs(r.r)>=.8?"Very strong association. Inspect the evidence and context before interpreting it.":"Meaningful association detected. Inspect the evidence before interpreting it."}</p><span className="explore">Inspect evidence ↗</span></button>)}</div></section>
    <section className="section"><div className="sectionHead"><div><span className="sectionTag">QUESTIONS</span><h2>Questions your data can answer</h2></div><span className="muted">Answers are generated from computed evidence</span></div><div className="questionGrid">{questions.map((q:any,i:number)=><button className="question" key={i} onClick={()=>setSelected(q)}><span className="qNum">{String(i+1).padStart(2,"0")}</span><div><b>{q.question}</b><small>{q.answer}</small></div><span>→</span></button>)}</div></section>
    <section className="section"><div className="sectionHead"><div><span className="sectionTag">VISUAL EVIDENCE</span><h2>See the patterns</h2></div><span className="muted">Labeled charts · computed from your data</span></div><div className="chartGrid">{charts.slice(0,6).map((c:any,i:number)=><article className="chart" key={i}><div className="chartHead"><div><b>{c.title}</b><small>{c.type} · {c.xKey} × {c.yKey}</small></div></div><Chart chart={c}/></article>)}</div></section>
    <section className="section"><div className="sectionHead"><div><span className="sectionTag">RELATIONSHIPS</span><h2>Where variables move together</h2></div></div><div className="relationshipList">{rels.slice(0,8).map((r:any,i:number)=><button key={i} onClick={()=>setSelected(r)}><span>{r.x}</span><div className="bar"><i style={{width:`${Math.min(100,Math.abs(r.r)*100)}%`}}/></div><b>{r.r.toFixed(2)}</b><span>{r.y}</span></button>)}</div></section>
    <section className="section"><div className="sectionHead"><div><span className="sectionTag">STATISTICS</span><h2>Distribution snapshot</h2></div><button className="exportBtn" onClick={exportClean}>Download cleaned XLSX</button></div><div className="statsTable">{summary.slice(0,12).map(s=><div key={s.column}><b>{s.column}</b><span>Mean {s.mean.toFixed(2)}</span><span>Min {s.min.toFixed(2)}</span><span>Max {s.max.toFixed(2)}</span><span>SD {s.std.toFixed(2)}</span></div>)}</div></section>
   </div>}
   {chat.length>0&&<section className="chatPanel">{chat.map((m,i)=><div className={m.role==="user"?"chatUser":"chatAssistant"} key={i}><b>{m.role==="user"?"You":"Gamur"}</b><p>{m.text}</p></div>)}</section>}
   </main><footer className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void sendChat()}}} placeholder="Ask Gamur about this analysis…"/><button onClick={()=>ref.current?.click()}>Attach data</button><button className="exportBtn" onClick={exportClean}>Clean & export</button><button className="run" disabled={busy} onClick={()=>prompt.trim()?void sendChat():void run()}>{busy?"Investigating…":prompt.trim()?"Ask →":"Re-run analysis"}</button></footer>
  </section>
  {selected&&<div className="modalShade" onClick={()=>setSelected(null)}><article className="detailPanel" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><span className="sectionTag">EVIDENCE DETAIL</span><h2>{selected.question||`${selected.x} and ${selected.y}`}</h2>{selected.r!==undefined&&<div className="detailMetric"><b>r = {selected.r.toFixed(2)}</b><span>{selected.strength||"Measured association"}</span></div>}<p>{selected.answer||`The measured correlation between ${selected.x} and ${selected.y} is ${selected.r.toFixed(2)}. This indicates association in the observed data; it does not by itself establish causation.`}</p><div className="answerNote">Computed from the saved analysis. Association does not by itself prove causation.</div></article></div>}
  {renameId&&<div className="modalShade"><article className="renamePanel"><h3>Rename analysis</h3><input autoFocus value={renameValue} onChange={e=>setRenameValue(e.target.value)}/><div><button onClick={()=>setRenameId(null)}>Cancel</button><button className="run" onClick={async()=>{try{const t=await token();const h=await renameHistory(t,renameId,renameValue.trim()||"Analysis");setHistory(x=>x.map(i=>i.id===h.id?h:i))}catch(e){setError(e instanceof Error?e.message:"Could not rename analysis.")}setRenameId(null)}}>Save name</button></div></article></div>}
  {deleteId&&<div className="modalShade"><article className="renamePanel"><h3>Delete this analysis?</h3><p>This permanently removes the saved history entry. The uploaded dataset is not deleted.</p><div><button onClick={()=>setDeleteId(null)}>Cancel</button><button className="run danger" onClick={()=>void deleteSaved()}>Delete</button></div></article></div>}
 </div>
}
