"use client";
import Link from "next/link";
import { useLanguage } from "../components/language-provider";

const content={
 en:[
  ["How Gamuur works","Think of Gamuur as a conversation layer over a serious data workflow. You can ask a general question first, then add a CSV or Excel file when you need evidence from your own data. For datasets, Gamuur can clean, analyze, forecast, explain, visualize, and report — and you choose which stages run."],
  ["Data analysis","Upload economic, business, survey, finance, education, health, agriculture, trade, population, or operational data. Ask for trends, averages, distributions, comparisons, relationships, missing values, outliers, growth rates, or the most important findings."],
  ["Forecasting","Use historical time-series data to prepare forecasting work. Ask which variables can be forecast, what assumptions matter, what the limitations are, and how future scenarios should be interpreted. Forecast models should be validated rather than treated as certainty."],
  ["AI insights","The AI explains computed results in plain language. It can turn statistics into a narrative, identify meaningful patterns, compare groups, explain possible drivers, suggest follow-up questions, and summarize what deserves attention. It should not invent numbers."],
  ["Visualization","Turn numeric relationships into useful charts and key metrics. Ask for a trend chart, comparison, distribution, relationship, or dashboard idea. Visuals are there to make evidence easier to understand, not to decorate a report."],
  ["Reports and decisions","Ask Gamuur to turn findings into an executive summary, research note, policy brief, business analysis, presentation outline, or decision memo. Always review assumptions and sources before using an output for a high-stakes decision."],
  ["Questions you can ask","Examples: What is happening in this dataset? Which region grew fastest? Compare 2020–2025. Find unusual observations. Explain the correlation. What should I investigate next? What does GDP growth mean? How do I read inflation data? What is Gamuur and how should I use it?"],
  ["Who can use Gamuur?","Students can learn concepts. Researchers can explore evidence. Economists can work with indicators. Policy teams can compare scenarios. Businesses can analyze sales and operations. NGOs can study programs and surveys. Journalists can investigate datasets. Leaders can ask for concise decision-ready summaries."],
  ["Data glossary","Row = one observation. Column = one variable. Mean = arithmetic average. Median = middle value. Correlation = how two variables move together, not proof of causation. Outlier = an observation far from the typical pattern. Forecast = an estimate of future values based on available information. KPI = a key performance indicator."],
  ["The Gamuur story","Gamuur is built around a simple idea: powerful analysis should be approachable. The goal is not to replace economists, researchers, analysts, or data scientists. The goal is to help more people ask better questions, understand evidence, and move from raw data to useful decisions."],
 ],
 so:[
  ["Sida Gamuur u shaqeeyo","Gamuur u arag inuu yahay wada sheekaysi dul saaran hab shaqo oo xogeed oo dhab ah. Waxaad marka hore weydiin kartaa su'aal guud, kadibna geli CSV ama Excel marka aad u baahan tahay caddayn ka timid xogtaada. Xogta Gamuur wuu nadiifin karaa, falanqayn karaa, saadaalin karaa, sharxi karaa, jaantus u samayn karaa, warbixinna ka samayn karaa — adiguna tallaabooyinka ayaad dooranaysaa."],
  ["Falanqaynta xogta","Soo geli xog dhaqaale, ganacsi, sahanno, maaliyad, waxbarasho, caafimaad, beeraha, ganacsiga dibadda, dadweyne, ama hawlgallo. Weydii isbeddellada, celcelisyada, kala duwanaanta, isbarbardhigga, xiriirrada, xog maqan, xog aan caadi ahayn, kobaca, ama natiijooyinka ugu muhiimsan."],
  ["Saadaalinta","Isticmaal xog taariikhi ah oo waqti-ku-xiran si aad u diyaariso saadaal. Weydii doorsoomayaasha la saadaalin karo, fikradaha muhiimka ah, xaddidaadaha, iyo sida xaaladaha mustaqbalka loo fasiri karo. Saadaashu waa qiyaas, ma aha xaqiiqo la hubo."],
  ["Aragtiyada AI","AI-gu wuxuu natiijooyinka xisaabeed ugu sharxaa luuqad fudud. Wuxuu sheegi karaa qaabab muuqda, isbarbardhigi karaa kooxo, sharxi karaa xiriirrada, soo jeedin karaa su'aalo xiga, wuxuuna samayn karaa soo koobid. Waa inuusan samayn tirooyin uusan xogtu taageerin."],
  ["Jaantusyada","Xiriirrada tirada u beddel jaantusyo iyo cabbirro muhiim ah. Weydii jaantus isbeddel, isbarbardhig, qaybin, xiriir, ama fikrad dashboard. Jaantusku wuxuu fududeeyaa fahamka caddaynta."],
  ["Warbixin iyo go'aan","Gamuur ka codso soo koobid maamul, qoraal cilmi-baaris, policy brief, falanqayn ganacsi, qaab bandhig, ama memo go'aan. Had iyo jeer hubi xogta, ilaha, iyo fikradaha muhiimka ah ka hor go'aan culus."],
  ["Su'aalo aad weydiin karto","Tusaale: Maxaa xogtan ka socda? Gobolkee ayaa ugu dhaqsaha badan u koray? Isbarbardhig 2020–2025. Raadi xogaha aan caadiga ahayn. Sharax correlation-ka. Maxaan baarayaa marka xigta? Waa maxay kobaca GDP? Sidee loo fahmaa sicir-bararka? Waa maxay Gamuur?"],
  ["Yaa isticmaali kara?","Ardaydu waxay ku baran karaan fikradaha. Cilmi-baarayaashu waxay sahmin karaan caddayn. Dhaqaaleyahannadu waxay la shaqayn karaan indicators. Kooxaha siyaasadda waxay isbarbardhigi karaan xaalado. Ganacsiyadu waxay falanqayn karaan iib iyo hawlgal. NGO-yadu waxay baari karaan barnaamijyo iyo sahanno."],
  ["Qaamuuska xogta","Row = hal observation. Column = hal variable. Mean = celcelis xisaabeed. Median = qiimaha dhexe. Correlation = sida laba doorsoome isu raacaan, mana aha caddayn sabab. Outlier = qiime ka fog qaabka caadiga ah. Forecast = qiyaas mustaqbal. KPI = cabbirka waxqabadka muhiimka ah."],
  ["Sheekada Gamuur","Gamuur wuxuu ku dhisan yahay fikrad fudud: falanqayn awood leh waa inay qof walba u fududaato. Ujeeddadu ma aha in lagu beddelo dhaqaaleyahannada, cilmi-baarayaasha, falanqeeyayaasha, ama data scientists. Ujeeddadu waa in dadka badan ay awoodaan inay weydiiyaan su'aalo fiican oo ay fahmaan caddaynta."],
 ],
 ar:[
  ["كيف يعمل Gamuur","فكّر في Gamuur كطبقة محادثة فوق سير عمل حقيقي للبيانات. يمكنك طرح سؤال عام أولًا، ثم إضافة ملف CSV أو Excel عندما تحتاج إلى أدلة من بياناتك. بالنسبة للبيانات، يستطيع Gamuur تنظيفها وتحليلها والتنبؤ بها وشرحها وتصويرها وإنشاء تقرير عنها — وأنت تختار المراحل التي تعمل."],
  ["تحليل البيانات","ارفع بيانات اقتصادية أو تجارية أو استبيانات أو مالية أو تعليمية أو صحية أو زراعية أو تجارية أو سكانية أو تشغيلية. اطلب الاتجاهات والمتوسطات والمقارنات والعلاقات والقيم المفقودة والقيم الشاذة ومعدلات النمو وأهم النتائج."],
  ["التنبؤ","استخدم السلاسل الزمنية التاريخية للتحضير للتنبؤ. اسأل عن المتغيرات القابلة للتنبؤ والافتراضات المهمة والقيود وكيفية تفسير السيناريوهات المستقبلية. التنبؤ تقدير مبني على المعلومات المتاحة وليس يقينًا."],
  ["رؤى الذكاء الاصطناعي","يشرح الذكاء الاصطناعي النتائج المحسوبة بلغة واضحة. يمكنه إبراز الأنماط ومقارنة المجموعات وشرح العلاقات واقتراح أسئلة متابعة وتلخيص ما يستحق الانتباه. يجب ألا يخترع أرقامًا غير مدعومة بالبيانات."],
  ["التصورات البيانية","حوّل العلاقات الرقمية إلى رسوم ومؤشرات مفيدة. اطلب رسم اتجاه أو مقارنة أو توزيع أو علاقة أو فكرة لوحة معلومات. الهدف هو تسهيل فهم الأدلة وليس تزيين التقرير."],
  ["التقارير والقرارات","اطلب من Gamuur إعداد ملخص تنفيذي أو مذكرة بحثية أو موجز سياسات أو تحليل أعمال أو مخطط عرض أو مذكرة قرار. راجع الافتراضات والمصادر قبل استخدام المخرجات في القرارات الحساسة."],
  ["أسئلة يمكنك طرحها","أمثلة: ماذا يحدث في هذه البيانات؟ أي منطقة نمت أسرع؟ قارن 2020–2025. ابحث عن القيم غير المعتادة. اشرح الارتباط. ماذا أبحث بعد ذلك؟ ما معنى نمو الناتج المحلي؟ كيف أقرأ التضخم؟ ما هو Gamuur وكيف أستخدمه؟"],
  ["من يستطيع استخدام Gamuur؟","يمكن للطلاب تعلم المفاهيم. يستطيع الباحثون استكشاف الأدلة. يمكن للاقتصاديين العمل مع المؤشرات. يمكن لفرق السياسات مقارنة السيناريوهات. تستطيع الشركات تحليل المبيعات والعمليات. ويمكن للمنظمات والصحفيين والقادة استخدامه لفهم البيانات وتلخيصها."],
  ["قاموس البيانات","الصف = ملاحظة واحدة. العمود = متغير واحد. المتوسط = المتوسط الحسابي. الوسيط = القيمة الوسطى. الارتباط = كيفية تحرك متغيرين معًا وليس دليلًا على السببية. القيمة الشاذة = ملاحظة بعيدة عن النمط المعتاد. التنبؤ = تقدير للقيم المستقبلية. KPI = مؤشر أداء رئيسي."],
  ["قصة Gamuur","بُني Gamuur على فكرة بسيطة: يجب أن يكون التحليل القوي سهل الوصول. الهدف ليس استبدال الاقتصاديين والباحثين والمحللين وعلماء البيانات، بل مساعدة المزيد من الناس على طرح أسئلة أفضل وفهم الأدلة والانتقال من البيانات الخام إلى قرارات مفيدة."],
 ]
} as const;

export default function LearnPage(){
 const {language,setLanguage,t}=useLanguage();
 const cards=content[language];
 return <main className="learnPage">
  <nav className="nav"><Link href="/" className="brand"><span>G</span> Gamuur</Link><div className="links"><Link href="/">{t.back}</Link><Link href="/workspace">{t.navWorkspace}</Link><Link href="/auth">{t.signIn}</Link><select value={language} onChange={e=>setLanguage(e.target.value as typeof language)} aria-label="Language"><option value="en">English</option><option value="so">Soomaali</option><option value="ar">العربية</option></select></div></nav>
  <header className="hero"><div className="eyebrow">GAMUUR LEARNING</div><h1>{t.learnTitle}</h1><p>{t.learnSubtitle}</p><div className="heroActions"><Link href="/" className="primary">{t.learnCta}</Link><a href="#guide" className="secondary">{t.topicHow}</a></div></header>
  <section id="guide" className="grid">{cards.map(([title,body],i)=><article key={title} className={i===0?"card featured":"card"}><div className="num">{String(i+1).padStart(2,"0")}</div><h2>{title}</h2><p>{body}</p></article>)}</section>
  <section className="use"><div><div className="eyebrow">USE CASES</div><h2>{language==="so"?"Hal meel, isticmaal badan.":language==="ar"?"مكان واحد، استخدامات كثيرة.":"One place, many ways to use it."}</h2></div><div className="useGrid">{(language==="so"?["Dhaqaale","Ganacsi","Cilmi-baaris","Waxbarasho","Siyaasad","Maaliyad","Sahanno","Warbaahin"]:language==="ar"?["اقتصاد","أعمال","بحث","تعليم","سياسات","تمويل","استبيانات","إعلام"]:["Economics","Business","Research","Education","Policy","Finance","Surveys","Media"]).map(x=><span key={x}>{x}</span>)}</div></section>
  <footer><Link href="/">Gamuur</Link><span>{t.topicHow} · {t.topicData} · {t.topicAI} · {t.topicReports}</span><Link href="/auth">{t.signUp}</Link></footer>
  <style jsx>{`:global(body){margin:0;background:#f6f8f4;color:#17201b;font-family:Inter,system-ui,sans-serif}.learnPage{min-height:100vh}.nav{height:72px;border-bottom:1px solid #dde3dc;display:flex;align-items:center;justify-content:space-between;padding:0 5vw;background:#f9faf7;position:sticky;top:0;z-index:10}.brand{font-weight:850;display:flex;gap:9px;align-items:center}.brand span{display:grid;place-items:center;width:31px;height:31px;background:#17201b;color:#fff;border-radius:9px}.links{display:flex;gap:22px;align-items:center;font-size:12px;color:#657068}.links a{text-decoration:none}.links select{border:1px solid #d7ddd5;border-radius:9px;padding:8px;background:#fff;color:#17201b}.hero{max-width:1050px;margin:auto;padding:105px 6vw 85px}.eyebrow{font-size:10px;font-weight:850;letter-spacing:.16em;color:#7c857e;margin-bottom:16px}.hero h1{font-size:clamp(55px,9vw,112px);letter-spacing:-.075em;line-height:.88;margin:0 0 25px}.hero p{max-width:760px;color:#68726a;font-size:18px;line-height:1.75}.heroActions{display:flex;gap:10px;margin-top:30px}.heroActions a{padding:12px 17px;border-radius:10px;text-decoration:none;font-weight:750;font-size:12px}.primary{background:#17201b;color:#fff}.secondary{border:1px solid #d5dcd4;color:#17201b;background:#fff}.grid{max-width:1050px;margin:0 auto;padding:0 6vw 90px;display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.card{background:#fff;border:1px solid #dde3dc;border-radius:18px;padding:27px;min-height:210px}.card.featured{grid-column:span 2;background:#eaf0e9}.num{font-size:10px;color:#909991;letter-spacing:.1em}.card h2{font-size:25px;letter-spacing:-.04em;margin:32px 0 12px}.card p{color:#69736b;line-height:1.7;margin:0;max-width:650px}.use{background:#17201b;color:#fff;padding:75px 6vw;display:grid;grid-template-columns:1fr 1fr;gap:50px}.use h2{font-size:clamp(35px,5vw,65px);letter-spacing:-.06em;line-height:.95;margin:0}.useGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.useGrid span{border:1px solid #3a443d;border-radius:10px;padding:14px;color:#dce3dc}footer{padding:28px 5vw;display:flex;justify-content:space-between;font-size:11px;color:#7c857e}footer a{text-decoration:none;color:inherit}@media(max-width:700px){.links a:nth-child(2){display:none}.hero{padding-top:70px}.grid{grid-template-columns:1fr}.card.featured{grid-column:span 1}.use{grid-template-columns:1fr}.hero h1{font-size:62px}footer{gap:15px;flex-wrap:wrap}}`}</style>
 </main>
}
