"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createSupabaseBrowserClient } from "../../lib/supabase-browser";
import { useLanguage } from "../components/language-provider";

export default function AuthPage(){
 const {t,language,setLanguage}=useLanguage(); const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const sb=createSupabaseBrowserClient();if(!sb)throw new Error(t.error);const result=await sb.auth.signInWithPassword({email,password});if(result.error)throw result.error;router.replace("/");router.refresh()}catch(err){setMessage(err instanceof Error?err.message:t.error)}finally{setBusy(false)}}
 return <main className="auth"><nav><Link href="/" className="brand"><span>G</span> Gamuur</Link><div><Link href="/learn">{t.navLearn}</Link><select value={language} onChange={e=>setLanguage(e.target.value as typeof language)}><option value="en">English</option><option value="so">Soomaali</option><option value="ar">العربية</option></select></div></nav><section className="box"><div className="eyebrow">GAMUUR ACCOUNT</div><h1>{t.signIn}</h1><p>{language==="so"?"Soo gal si aad u tijaabiso Gamuur.":language==="ar"?"سجّل الدخول لاختبار Gamuur.":"Sign in to test Gamuur."}</p><form onSubmit={submit}><label>{t.email}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" /></label><label>{t.password}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} autoComplete="current-password" /></label><button className="submit" disabled={busy}>{busy?"…":t.login}</button></form>{message&&<div className="message">{message}</div>}<Link href="/" className="back">← {t.back}</Link></section><style jsx>{`:global(body){margin:0;background:#f6f8f4;color:#17201b;font-family:Inter,system-ui,sans-serif}.auth{min-height:100vh}.auth nav{height:72px;border-bottom:1px solid #dde3dc;display:flex;justify-content:space-between;align-items:center;padding:0 6vw}.auth nav div{display:flex;gap:18px;align-items:center;font-size:12px;color:#68726a}.auth nav a{text-decoration:none}.brand{font-weight:850;display:flex;gap:9px;align-items:center;color:#17201b}.brand span{display:grid;place-items:center;width:31px;height:31px;background:#17201b;color:#fff;border-radius:9px}.auth select{border:1px solid #d5dcd4;border-radius:9px;padding:8px;background:#fff}.box{width:min(460px,calc(100% - 36px));margin:10vh auto;padding:38px;background:#fff;border:1px solid #dce2db;border-radius:20px;box-shadow:0 20px 70px rgba(23,32,27,.06)}.eyebrow{font-size:10px;font-weight:850;letter-spacing:.16em;color:#7d867f}.box h1{font-size:43px;letter-spacing:-.06em;margin:17px 0 10px}.box>p{color:#69736b;line-height:1.6;font-size:13px}form{display:grid;gap:15px;margin-top:25px}label{display:grid;gap:7px;font-size:11px;font-weight:750}input{border:1px solid #d3dad2;border-radius:9px;padding:12px;font:inherit;outline:none}.submit{border:0;background:#17201b;color:#fff;border-radius:10px;padding:13px;font-weight:800;cursor:pointer}.submit:disabled{opacity:.5}.message{margin-top:15px;padding:12px;border-radius:9px;background:#eef2ed;color:#566158;font-size:11px;line-height:1.5}.back{display:block;margin-top:22px;font-size:11px;color:#747e76;text-decoration:none}@media(max-width:600px){.box{margin-top:7vh;padding:25px}.box h1{font-size:36px}}`}</style></main>
}
`}