const API_BASE_URL=((process.env.NEXT_PUBLIC_API_BASE_URL??"/api").trim()||"/api").replace(/\/$/,"");
export type BackendHealth={status:string;service:string};
export type Project={id:string;name:string;description:string|null;status:string};
export type Dataset={id:string;project_id:string;name:string;source_type:string;description:string|null;current_version:number;created_at:string;updated_at:string};
export type HistoryItem={id:string;project_id:string;title:string;mode:string;created_at:string;dataset_id?:string|null;result?:IntelligenceResult};
export type IntelligenceResult={stages:string[];dataset:{rows:number;columns:number};cleaning?:{changes:string[];rows_after:number};analysis?:{rows:number;columns:number;numeric_columns:string[];categorical_columns?:string[];summary:Array<{column:string;count:number;missing?:number;unique?:number;mean:number;median?:number;std:number;variance?:number;min:number;q1?:number;q3?:number;max:number;range?:number;iqr?:number;p05?:number;p10?:number;p90?:number;p95?:number}>;categorical_summary?:Array<{column:string;count:number;missing:number;unique:number;mode?:string|null;top_values:Array<{value:string;count:number;share:number}>}>;correlations:Record<string,Record<string,number|null>>;target?:string|null;relationships?:Array<{x:string;y:string;r:number;strength:string}>;pairs?:Array<{x:string;y:string;r:number;strength?:string}>;outliers?:Array<{column:string;count:number;rate:number;lower?:number;upper?:number}>;date_columns?:Array<{column:string;coverage:number;min:string;max:string;frequency_hint:string}>};questions?:Array<{question:string;answer:string;type?:string}>;forecasting?:{status:string;reason?:string;horizon_min_years?:number;horizon_max_years?:number;date_column?:string|null;target?:string|null;observations?:number;history_start?:string;history_end?:string;history_years?:number;frequency?:string;numeric_series?:string[]};insights?:string;insight_provider?:string;visualization?:{visuals?:Array<any>;charts:Array<{type:string;title:string;xKey:string;yKey:string;data:Array<Record<string,any>>}>;relationships?:Array<{x:string;y:string;r:number;strength:string}>;recommended?:string};report?:{title:string;prompt:string;analysis:unknown;insights?:string;questions?:unknown[]}};
export type ForecastResult={status:string;target:string;date_column:string;horizon_years:number;frequency:string;method:string;backtest_rmse:number;residual_std:number;historical:Array<{date:string;actual:number}>;forecast:Array<{date:string;forecast:number;lower:number;upper:number}>;caution:string};
type RequestOptions=RequestInit&{token?:string};
async function request<T>(path:string,options:RequestOptions={}):Promise<T>{const headers=new Headers(options.headers);headers.set("Accept","application/json");if(options.body&&!(options.body instanceof FormData))headers.set("Content-Type","application/json");if(options.token)headers.set("Authorization",`Bearer ${options.token}`);const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers,cache:"no-store"});if(!response.ok){let detail=`Request failed (${response.status})`;try{const body=await response.json();detail=body.detail?.message??body.detail??detail}catch{}throw new Error(typeof detail==="string"?detail:JSON.stringify(detail))}if(response.status===204)return undefined as T;return response.json() as Promise<T>}
export const getBackendHealth=()=>request<BackendHealth>("/health");
export const getProjects=(token:string)=>request<Project[]>("/projects",{token});
export const createProject=(token:string,name:string)=>request<Project>("/projects",{method:"POST",token,body:JSON.stringify({name,description:null,settings:{}})});
export const getDatasets=(token:string,projectId:string)=>request<Dataset[]>(`/projects/${projectId}/datasets`,{token});
export async function uploadDataset(token:string,projectId:string,name:string,file:File){const form=new FormData();form.append("name",name);form.append("file",file);return request<Dataset>(`/projects/${projectId}/datasets`,{method:"POST",token,body:form})}
export async function createDatasetVersion(token:string,projectId:string,datasetId:string,file:File){const form=new FormData();form.append("file",file);return request<any>(`/projects/${projectId}/datasets/${datasetId}/versions`,{method:"POST",token,body:form})}
export const runIntelligence=(token:string,projectId:string,datasetId:string,prompt:string,stages:string[])=>request<IntelligenceResult>(`/projects/${projectId}/intelligence/run`,{method:"POST",token,body:JSON.stringify({dataset_id:datasetId,prompt,stages})});
export const runForecast=(token:string,projectId:string,datasetId:string,horizonYears:number,target?:string,dateColumn?:string)=>request<ForecastResult>(`/projects/${projectId}/intelligence/forecast`,{method:"POST",token,body:JSON.stringify({dataset_id:datasetId,horizon_years:horizonYears,target:target||null,date_column:dateColumn||null})});
export async function downloadCleanDataset(token:string|Promise<string>,projectId:string,datasetId:string,format:"xlsx"|"csv"="xlsx"){const authToken=await token;if(!authToken)throw new Error("Your session has expired. Please sign in again.");const response=await fetch(`${API_BASE_URL}/projects/${projectId}/intelligence/cleaned/${datasetId}?format=${format}`,{headers:{Authorization:`Bearer ${authToken}`},cache:"no-store"});if(!response.ok){let detail=`Could not download cleaned dataset (${response.status})`;try{const body=await response.json();detail=body.detail?.message??body.detail??detail}catch{}throw new Error(typeof detail==="string"?detail:JSON.stringify(detail))}const blob=await response.blob();const disposition=response.headers.get("content-disposition")||"";const match=disposition.match(/filename="?([^";]+)"?/i);const filename=match?.[1]||`gamur-cleaned.${format}`;const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
export const getHistory=(token:string)=>request<HistoryItem[]>("/history",{token});
export const createHistory=(token:string,projectId:string,title:string,mode="full",datasetId?:string,result?:IntelligenceResult)=>request<HistoryItem>(`/history/projects/${projectId}`,{method:"POST",token,body:JSON.stringify({title,mode,dataset_id:datasetId||null,result:result||{}})});
export const renameHistory=(token:string,id:string,title:string)=>request<HistoryItem>(`/history/${id}`,{method:"PATCH",token,body:JSON.stringify({title,mode:"full"})});
export const deleteHistory=(token:string,id:string)=>request<void>(`/history/${id}`,{method:"DELETE",token});
export const askData=(token:string,message:string,context="")=>request<{answer:string;language:string;ai_provider?:string}>("/chat",{method:"POST",token,body:JSON.stringify({message,language:"en",context})});
export {API_BASE_URL};
